spring:
  application:
    name:
      social-network
  server:
    port: ${SERVER_PORT:8080}

  # Postgres
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres

    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jackson:
    serialization:
      write-dates-as-timestamps: false

  # Migration properties
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8080}


# Cors config
app:
  cors:
    allowed-origins:
      - http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE
    allowed-headers: Authorization,Content-Type
    allow-credentials: true

logging:
  level:
    org:
      springframework:
        security: debug
        web: debug